{% set name = "presto-server" %}
{% set version = "0.284" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  # Build needs a proper Git checkout.
  git_url: https://github.com/prestodb/presto
  git_rev: "{{ version }}"

build:
  number: 0
  noarch: generic
  script:
    - sed -i'' -e 's@<module>presto-docs</module>@@g' pom.xml && ./mvnw clean install -DskipTests
    - ./mvnw org.codehaus.mojo:license-maven-plugin:aggregate-add-third-party
    - mv presto-server/target/presto-server-*/presto-server-* $PREFIX/opt/presto-server
    - echo "exec \"$PREFIX/opt/presto-server/bin/launcher\" \"\$@\"" > $PREFIX/bin/presto-server && chmod +x $PREFIX/bin/presto-server
  missing_dso_whitelist:
    # From libprocname, which is shipped as part of Presto
    - /lib64/libc.so.6  # [linux]

requirements:
  build:
    - git-lfs
    - openjdk >=8,<18
    - maven >=3.3.9
  run:
    - openjdk
    - python >=2.4
    - __unix

test:
  commands:
    - presto-server --help

about:
  home: https://prestodb.io
  summary: Fast and Reliable SQL Engine for Data Analytics and the Open Lakehouse
  description: |
    Presto is a distributed SQL query engine designed to query large data sets distributed over one or more heterogeneous data sources.
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-sources/license/THIRD-PARTY.txt
  doc_url: http://prestodb.github.io/docs/current/index.html
  dev_url: https://github.com/prestodb/presto

extra:
  recipe-maintainers:
    - jonashaag
